### ISSUE TITLE
ゲームスタート時にアイコンが二重表示されるバグ修正

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#131]
部屋のオーナーにのみ発生。
feature/roll_diceブランチで既に解消している可能性があります。
まずはご確認の上、再現しないようでしたらCloseしてください。

**Comment by lachelier** [comment]
feature/roll_diceブランチで既に解消している可能性あり。

**Comment by favopg** [comment]
１個バグをつぶせたのと、確認の同意がとれたのでクローズします。
