### ISSUE TITLE
CircleCIの設定ファイル作成

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#14]
以下の記事やサンプルコードを参照しながら設定ファイルの作成をお願いします！
https://circleci.com/docs/2.0/language-php/ 
https://php-junkie.net/framework/laravel/built-environment/

サンプルコード
\# PHP CircleCI 2.0 configuration file
\#
\# Check https://circleci.com/docs/2.0/language-php/ for more details
\#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      # prepare the database
      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=sqlite_testing --force

      # run tests with phpunit or codecept
      #- run: ./vendor/bin/phpunit
      - run: ./vendor/bin/codecept build
      - run: ./vendor/bin/codecept run

**Comment by lachelier** [comment]
確認の都合上、一旦プルリクをマージさせていただきました💦
.circleciディレクトリはリポジトリのルートディレクトリ下におく必要があるので、src下から移動をお願いします！

**Comment by stkzk3110** [comment]
お、了解です〜！

**Comment by lachelier** [comment]
@stkzk3110 
エラー共有します！

#!/bin/sh -eo pipefail
# Unable to parse YAML
# while parsing a block collection
#  in 'string', line 6, column 7:
#           - image: circleci/php:7.4-node-b ... 
#           ^
# expected <block end>, but found '?'
#  in 'string', line 8, column 7:
#           command: mysqld --default-authen ... 
#           ^
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false

**Comment by lachelier** [comment]
すみません、横着して編集せずに貼りつけたらすごいことになりました笑

**Comment by stkzk3110** [comment]
続きは明日やります〜

**Comment by stkzk3110** [comment]
マージ済みのためクローズします。
