### ISSUE TITLE
リレーション

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#21]
※ 先に #30 を完了させてください。

Room, User, Boardの各モデルクラスのリレーションの定義をお願いします

参考
https://readouble.com/laravel/6.x/ja/eloquent-relationships.html
https://drive.google.com/file/d/1q3Dow_OuUaiqy9FjAIQMsM4rtIxr-6qN/view?usp=sharing

**Comment by stkzk3110** [comment]
#30 マージ待ち。

**Comment by lachelier** [comment]
@stkzk3110 
すみません、プルリクの内容にRoomのリレーションが抜けてたのを見落としてIssueクローズしちゃいました💦こちらでやっておきます！

**Comment by lachelier** [comment]
その他諸々間違ってたの直しました！てきとうにマージしちゃってごめんなさい💦

**Comment by stkzk3110** [comment]
お、マジですか😢
すみません、お手数おかけします🙌
ボスが直したの勉強のために後でマージされたら見ておきます！
