### ISSUE TITLE
room_userテーブルのマイグレーション作成

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#30]
## テーブル構造
id: 符号なしBIGINTを使用した自動増分ID（主キー）
room_id: roomsテーブルのidカラムを参照
user_id: usersテーブルのidカラムを参照
go: 符号なしTINYINT
status: 符号なしTINYINT
position: 符号なしTINYINT

room_idとuser_idは複合ユニーク

## 参考
https://readouble.com/laravel/6.x/ja/migrations.html

**Comment by stkzk3110** [comment]
マージ済のため、クローズします。
