### ISSUE TITLE
👑入室処理作成

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#33]
## 先に完了が必要なIssue
#21 #31 #32

## 実装場所
RoomRepositoryクラスに新しいメソッドを作成

## 実装内容
ユーザIDと部屋IDを引数で受け取る。

部屋のmember_countがmax_member_count以上ならfalseを返す。
また、room_userテーブルに既に同じユーザと同じ部屋のペアで保存されていてもfalseを返す。
これらに該当しなければ次の処理を続ける。

room_userテーブルに以下のように挿入する。
- （id: 自動インクリメント）
- room_id: 引数で渡されたやつ
- user_id: 引数で渡されたやつ
- go: 0
- status: 健康（ #32 で定義された定数を利用）
- position: 1

部屋のmember_countを1増やす。

trueを返す。

## テスト
- member_countがmax_member_count以上ならfalseが返ってくる
- room_userテーブルに既に同じユーザと同じ部屋のペアで保存されていてもfalseが返ってくる
- 上記以外の場合、trueが返ってくる。かつ、room_userテーブルに新しいデータが保存されている。部屋のmember_countが1増えている。

**Comment by stkzk3110** [comment]
#31 マージ後、対応します〜！
