### ISSUE TITLE
部屋のオーナーを参加させる

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#36]
## 先に完了が必要なIssue
#33 

## 実装内容
部屋を作成した際に、#33で作成した機能を使ってオーナーを部屋の参加者として登録する

## テスト
- 部屋を作成した後、オーナーが参加者として登録されている
- 部屋を作成した後、部屋の参加人数が1になっている

**Comment by stkzk3110** [comment]
オーナーを部屋の参加者として登録する
→room_userテーブルに追加する。

**Comment by stkzk3110** [comment]
実装箇所は、以下のRoomRepository.phpのaddMember()の
$room->users()->attach($userId,[
            'go' => 0,
            'status' => config('const.piece_status_health'),
            'position' => 1
        ]);
の部分です。

![スクリーンショット 2020-05-19 午後7 40 43](https://user-images.githubusercontent.com/36589062/82317320-05bee080-9a09-11ea-8e16-519e23d86077.png)

**Comment by lachelier** [comment]
@stkzk3110 
入室処理は #33 でご用意（RoomRepositoryクラスのaddMember()メソッド）いただきましたが、
部屋を作成したときにオーナーは入室していないと思うので
RoomControllerクラスのstore()メソッドでaddMember()メソッドを実行してほしいです！

また、その際room_idが必要になると思いますので、RoomRepositoryクラスのcreate()メソッドも作成したroomのidを返すようにご変更ください🙏

**Comment by stkzk3110** [comment]
あ、そっか。
処理として入室するための処理は作ったけど実際にユーザーが部屋を作るボタンを押して入室したっていうのを実行する場所がそもそもないからそこが必要って話ですね！
理解しました。
