### ISSUE TITLE
unameからRoomオブジェクトを取得できるメソッドを作成

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#48]
RoomRepositoryクラス
findByUname($uname)メソッド

引数の$unameがroomsテーブルのunameカラムと一致するデータを取得して、Roomオブジェクトを返してください。
また、そのテストコードも実装をお願いします！
※テストコードは、削除済み（deleted_atがNULLでない）の部屋は取得できないこともご確認をお願いします

**Comment by stkzk3110** [comment]
こちらマージ済なのでクローズします。
