### ISSUE TITLE
部屋ページの表示

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#49]
## 先に完了が必要なIssue
#25 

## パス
/room/{uname}

## 実装してほしいこと
- RoomControllerクラスにshow($uname)メソッドを作成。
- RoomRepositoryクラスのfindByUname()メソッドを使って、Roomオブジェクトが存在すればそれをviewテンプレートに渡す。Roomオブジェクトがなければ404エラーを返す。
- ユーザが部屋の参加者ではない場合は、404エラーを返す。
- テンプレートはresources/views/room/show.blade.phpを新規作成（中身は空でOK）。
- 上記を満たしていることを確認できるテストコード

**Comment by favopg** [comment]
@lachelier 
部屋ページの実装について、#49_issi_developブランチにコミットしたのでご確認いただきたいです。（テストに入る前に実装が正しくないと意味ないと思うので、、、）
※テストコード未対応のためプルリクは送っていません。

テストコードについて１点質問です。
#49の対応では、RoomControllerクラスしか対応を行っていないので、テストコードはRoomController用のテストクラスを用意するべきかなと思ったのですが認識違いますでしょうか？

他メソッド(store等)のテストコードを書いてる該当クラスが見つからなかったため、どこのテストクラスに書くべき？で止まってしまったのでご教授いただけると幸いです。
よろしくお願いいたします。

**Comment by lachelier** [comment]
@favopg 
ご確認ありがとうございますー！

やりたい方向性はあってます！
コメントつけたところの修正と、以下の実装もお願いします🙏
> ユーザが部屋の参加者ではない場合は、404エラーを返す。

※ #33 で作成中のRoomRepositoryクラスのisMember()メソッドを使うと良いと思うので、ここは#33の修正が終わってからでも良いかもです

> #49の対応では、RoomControllerクラスしか対応を行っていないので、テストコードはRoomController用のテストクラスを用意するべきかなと思ったのですが認識違いますでしょうか？
コントローラ系は、単体テストではなく機能テストで大丈夫です！
tests/Feature/RoomTest.phpへメソッドを追加する形でお願いします:)

処理の内容は全然ちがいますが、処理の流れとしてはtestUserCanCreateRoom()メソッドが参考になるかもしれません。

よろしくお願いしますー！

**Comment by favopg** [comment]
@lachelier 
ご確認いただきありがとうございます。
指摘修正と追加の実装をしたので、ご確認いただきたいです。

テストコードで質問なのですが、３テストケース追加してみたのですが、失敗原因がよくわからないのでコードを見ていただきたいです。

【追加したテストケース①】
・パラメータunameに該当しない部屋が存在しない場合は404に行くことを確認
　→結果が302（リダイレクト）で返却されていて理由がわからず、、
　　$this->get('/room/囲碁')でコントローラが呼べてる想定でいたのですが違いますか？

【追加したテストケース②】
・パラメータunameに該当しない部屋が存在する場合はshowにリダイレクト
　→結果にviewがいないと返却されていて、レスポンスに想定した内容が入っていない気がするのと、①と同じ課題（エラー確認方法がわからず、、、 ）

【追加したテストケース③】
・パラメータunameに該当しない部屋が存在するかつすでに入室している場合は404
→room_userテーブルにテストデータを用意しよう試みたが、失敗、、、Roomを参考に同じように書いてみたけど、作成方法が違いますかね、、、？

上記、考えたテストケースが見当違いであればテストコード作るのは厳しいので巻き取っていただきたいです。
よろしくお願いいたします。

**Comment by lachelier** [comment]
@favopg 
全体的に惜しいですね＞＜
あと2,3回やってみるとスラスラ書けるかもです！

###  testNotExistRoomFromUnameTo404Page()

>$this->get('/room/囲碁')

基本はこれでOKです！
ただ、このページの場合はアカウント認証が必要なので、ログインページにリダイレクトされてしまっている状態です。

下記の記事を参考に、actingAs()メソッドを使ってみてください:)
https://readouble.com/laravel/6.x/ja/http-tests.html#session-and-authentication

あと、ここでは$boardと$roomは作らなくても大丈夫です。

 ### testExistRoomFromUnameNotMemberToRedirectShow()

> unameに該当する部屋が存在するかつ入室していない場合はshowにリダイレクトする

正しくは、「unameに該当する部屋が存在するかつ入室していない場合は404エラー」になります！入室処理が済んでいるの人しかその部屋の中身を見られないイメージです。

#### 作成した部屋にアクセスする

get('/room/'.uniqid())だとuname部分が作った部屋と一致しなくなるので
get('/room/'.$room->uname)ってしてあげると作った部屋にアクセスすることができます✨
uniqid()についての参考記事：https://www.php.net/manual/ja/function.uniqid.php

### testExistRoomFromUnameNotMemberToRedirectShow() 

> unameに該当する部屋が存在するかつ入室している場合は404にリダイレクト

正しくは、「unameに該当する部屋が存在するかつ入室している場合は200（正常ステータス）」になります！（200ステータスの確認の代わりに、showテンプレートが表示されていることを確認でもOKです）

room_userテーブルはroomsテーブルとusersテーブルの中間テーブルで、挿入方法がちょっとややこしいので
RoomRepositoryクラスに新しくできたaddMember()メソッドを使って入室させてしまいましょう🙌

#### 入室処理

```
$repository = new RoomRepository();
$repository->addMember($user->id, $room->id);
```
