### ISSUE TITLE
部屋を作成後に、部屋ページにリダイレクトさせる

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#50]
## 先に完了が必要なIssue
#36 #49

## 要件
- 部屋を新規作成したユーザは、作成成功後に部屋ページへリダイレクトされる
- 上記項目を確認できるテスト

**Comment by favopg** [comment]
@lachelier 
すんなり行けるかなと思ったのですが、つまいづいちゃったのでご教授いただきたいです。
storeメソッド内の修正内容を確認していただきたいです。
対応ブランチは下記になります。
feature/#50_issi_develop

リダイレクト処理入れてみたけど、画面切り替わらず、、、、
お手数おかけいたしますが、よろしくお願いいたします。

**Comment by lachelier** [comment]
@favopg 
routes/web.phpで定義してある、普通にブラウザでアクセスするメソッドなら実装していただいた方法であってます！
ただ、今回のstoreメソッドはAPI用のメソッドになるので、コントローラでredirect()メソッドを返してもリダイレクト処理が正常に動作しません。

今回のような場合は、結果を受け取ったvueコンポーネントのJavaScript部分にリダイレクト処理を書いてあげると良いです🙌

1.  store()メソッドの返り値を一旦元に戻す
1. 返り値のjsonデータに作成したテーブルのunameを含める
1. vueコンポーネントのscript内にある、APIの結果を受け取っているところに"statusがsuccessなら/room/{uname}にリダイレクトする"処理を書く
こんな感じでいけると思います！（いけなかったらまたご連絡ください）

**Comment by favopg** [comment]
@lachelier 
ご教授いただきありがとうございます！
手順通りに修正したら実現できました！
実装は完了したのですが、テストコードで手が止まっちゃいました、、、ので再度ご相談、、、させてください。

【前提】
リダイレクトはvue側で行っているのでテストコードでは表現できない

【不明点】
・テストとして何を確認できれば良いかわかっていない
　→apiコールした後の戻り値であるjsonの中身を確認できれば良い？
　　→json結果の「uname」はapi実行後に発行されるユニークキーなので確認できないような・・・・

大変お手数ですが、ご確認のほどよろしくお願いいたします。

**Comment by lachelier** [comment]
@favopg 
実装ありがとうございますー！🙌

Laravel Duskを使ったブラウザテストを想定していましたが、ご提案のjsonの中身を確認でも良いかもしれません✨
json結果のunameと、ユーザが作成した部屋のunameが一致しているかどうかをテストしていただく感じでいかがでしょう？
ユーザが作成した部屋のunameは、RoomRepositoryクラスのgetOwnRoom()メソッドを使うと取得できる気がします:)
