### ISSUE TITLE
ログイン後のリダイレクト先を変更する

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#64]
現在、ログインすると/homeにリダイレクトされますが
有効な部屋に入室済みのユーザはその部屋（/room/{uname}）に、そうでないユーザは/roomsにリダイレクトするように変更してください。
また、そのテストコードもお願いします！

**Comment by stkzk3110** [comment]
●メモ書き
・未ログイン状態からログイン(アカウント登録後の遷移先)したときのリダイレクト
→(/rooms)に遷移するように設定。
・ログイン済み状態からログイン画面に遷移しようとしたときのリダイレクト
→ログイン済み状態で/login画面に行こうとすると/roomsにリダイレクトするように設定。

**Comment by stkzk3110** [comment]
部屋に入室済みユーザーのログイン後のリダイレクト先のテストがルートURLになってしまうため一旦保留。

これはちょっとまた時間あるときにみます。
