### ISSUE TITLE
ユーザーが部屋に参加できるページを作成する

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#65]
パス: /room/{uname}/join
ミドルウェア: auth
コントローラ: RoomControllerクラス join()メソッド
メソッド: GET
実装内容: 
- アクセスした部屋のdeleted_atがNULLでなければ、404エラーを返す
- RoomRepositoryクラスのisMember()の返り値がtrueなら、/room/{uname}にリダイレクト
- RoomRepositoryクラスのaddMember()を実行
- addMember()の返り値がfalseなら、「入室できませんでした」エラー表示
- addMember()の返り値がtrueなら、/room/{uname}にリダイレクト

上記を満たすことを確認できるテストコードもお願いします！

**Comment by lachelier** [comment]
すみません、メソッド書き忘れていたので追記しました！

**Comment by favopg** [comment]
> すみません、メソッド書き忘れていたので追記しました！
あれ、、、どこの話でしょうか？
あと下記に、ちゃっかり質問を投げているのでご確認いただきたいです。（通知いってないですかね・・・・）
https://github.com/lachelier/sugoroku/commit/25dc1cdb2d605746ec9e72e8d80f6a8196441419

**Comment by lachelier** [comment]
@favopg 
> メソッド: GET
これでした！実装もGETになっていたので大丈夫でした🙌

> 通知いってないですかね・・・・
遅くなってすみません！今返答しました！
実はメールほとんど確認できてないです、、、💦
Issueの方はちらちら見てるので、こちらに書いていただけると気づくの早いかもです＞＜
