### ISSUE TITLE
部屋の参加者を返すAPI作成

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#69]
アクセス権限：ログイン済みユーザ
パス：/api/room/{uname}/get_members
unameで指定された部屋の参加者をjson形式で返すコードと、それを確認できるテストコードもお願いします！

**Comment by lachelier** [comment]
参加者データは、room_userのすべてのカラムの取得をお願いします！

**Comment by wollllll** [comment]
了解いたしました！

**Comment by wollllll** [comment]
すいません、どうしてもわからないので質問させてください。。。。
api.phpにて指定通りのルーティングを切りました。
```
Route::middleware('auth:api')->get('/room/{uname}/get_members', 'RoomController@getMembers');
```

**Comment by lachelier** [comment]
'auth:api'ミドルウェアを利用しているため、認証トークンの受渡しが必要です。
resources/js/components/partials/createRoomModal.vueのdoSend()や
resources/js/components/partials/action.vueのstart()等でもapiと通信していますので、参考にしてみてください:)

**Comment by wollllll** [comment]
ありがとうございます！確認してみます！！

**Comment by lachelier** [comment]
仕様変更メモ
ルーティングを/api/get_member/{roomID}/{userID}にして
リポジトリのメソッドを参加者全員じゃなくてroomIDとuserIDでヒットしたroom_userデータ1つを返す

**Comment by wollllll** [comment]
すいません、昨晩奮闘したのですが、結局分からずじまいという感じになってしまっております。。。

現状ルーティングを
```
Route::middleware('auth:api')->get('/get_member/{roomID}/{userID}', 'RoomController@getMember');
```
[としており、コントローラーのほうは仮でこうしております。
```
    public function getMember(int $roomID, int $userID)
    {
        return response()->json('test');
    }
```
そして、action.vueのstartメソッドのすぐ下にget_memberメソッドを作成しました。
```
    getMember: function () {
      axios.defaults.headers.common['Authorization'] = "Bearer " + this.token;
        axios.get(
          '/api/get_member' + this.room.id + '/' + this.user_id,
          {
            headers: {
              "Content-Type": "application/json"
            },
          }).then(function(response) {
              console.log(response.data)
          }).catch(function(error) {
              console.log(error);
        });
    }
```
この状態で/api/get_member/{roomID}/{userID}アクセスすればconsoleに"test"とかえって来るかと思っていたのですが、何か検討違いしてますでしょうか？

**Comment by lachelier** [comment]
@wollllll 
ざっと見た感じですと書き方はあっているように思います！

> /api/get_member/{roomID}/{userID}アクセスすれば

念のため確認ですが、ブラウザから/api/get_member/{roomID}/{userID}にアクセスしようとしているのではなくgetMember()を実行しているという認識であっていますか？

また、その際何かエラーは表示されていますか？

**Comment by wollllll** [comment]
すいません、紛らわしい言い方してました。。getMember()を実行ですね。ボタンとかをきっかけに実行してないので、room/showを表示したタイミングで自動的にgetMember()が実行されるという認識です。エラーについては一件何か出てますが、今回の場所とか関係ないような気がします。。

**Comment by wollllll** [comment]
![2020-05-26](https://user-images.githubusercontent.com/54100964/82825629-8b99ca80-9ee6-11ea-8572-b79f90dc2f48.png)

**Comment by lachelier** [comment]
@wollllll 
なるほどです！
エラーが出たタイミングで処理が中断されている可能性もありますね。getMember()の一番最初にconsole.log()でてきとうな文字列を出力して、メソッドが確実に実行されていることをまず確認されるのはいかがでしょう？
あと、そのエラーはたぶんmasterで解消されていると思うので、もしそこが原因でしたら一度マージされると良いかもしれません:)

**Comment by wollllll** [comment]
お疲れ様です。先ほどconsole.logで確認したんですが、表示されなかったのでメソッド自体が実行されてないっぽいですね。。最新の取得したら上記のエラーは消えたんですが、今度はdelete()周りでエラーが出始めました。。。。。一度現状の状態をpushしたので、もしよろしければむちょこさんの環境でご確認いただくことて可能でしょうか？

**Comment by lachelier** [comment]
@wollllll 
承知致しました！もしかしたら明日になっちゃうかもですが、拝見しますね！

**Comment by lachelier** [comment]
@wollllll 
すみません、delete()は他の方のpushに混ざっていて誤ってマージしてしまったもので、今はaction.vue自体消しました、、、💦
（対応していただいている間に周辺コードをちょこちょこ変えてしまいました＞＜）

結論だけ言うと、こんな感じにしていただくと動くはずです！

1. masterブランチの最新コードを持ってくる。
2. /resources/js/components/partials/sugoroku.vueのmethodsの中にメソッドを作成し、以下のように書く

```
        axios.defaults.headers.common['Authorization'] = "Bearer " + this.token;
        axios.get('/api/get_member/' + this.room.id + '/' + （ユーザID）, {
            headers: {
                "Content-Type": "application/json"
            }
        }).then(function (response) {
            console.log(response)
        }).catch(function(error) {
            console.log(error);
        });
```

あるいは、Discordにも書いた通り一旦ルーティングのミドルウェア部分を消してブラウザで出力を確認していただくのも良いかもしれません:)

**Comment by lachelier** [comment]
今日似たようなのを作ったので、こちらを参考にしていただくのも良いかもです！

- ルーティング（routes/api.php）：Route::middleware('auth:api')->get('/sugoroku/members/{room_id}', 'SugorokuController@getMembers');
- コントローラ：SugorokuControllerクラスgetMembers()メソッド
- 実行：/resources/js/components/partials/sugoroku.vueのgameStart()メソッド

**Comment by wollllll** [comment]
何度もすいません。。上記参考に進めてみます！

**Comment by wollllll** [comment]
進展がありましたのでご報告です。ボタンが押されたらgetMember()メソッドを実行みたいな感じでしたら想定通りの挙動をしました。ただ本来は画面が読み込まれたタイミングで勝手に実行という流れなのですが、なぜそうならないのかが謎といった感じです。。

あと一点質問なのですが、ルーティングこうなってるんですが、
```
Route::middleware('auth:api')->get('/get_member/{roomID}/{userID}', 'RoomController@getMember');
```
このユーザーIDのところなんですが、ユーザーが複数いる部屋の場合誰を対象にすればいいんでしょうか？authのidでしょうか？

**Comment by wollllll** [comment]
vue.jsについてまったく詳しくなかったので、色々調べていたらライフサイクルという概念に行きました。そこで色々見てたらmountedの中に書かれたものは画面読み込んでdom生成後に実行されるとあったので、
```
        axios.defaults.headers.common['Authorization'] = "Bearer " + this.token;
        axios.get('/api/get_member/' + this.room.id + '/' + (ユーザーID), {
            headers: {
                "Content-Type": "application/json"
            }
        }).then(function (response) {
            if (response.data.status === 'success') {
                console.log(response.data.roomUser);
            }
        }).catch(function(error) {
            console.log(error);
        });
```
このapi通信してる部分をそのまま貼り付けたら、画面読み込み直後api通信することができました。これで大丈夫なんでしょうか、、、？

**Comment by wollllll** [comment]
https://github.com/lachelier/sugoroku/pull/130
現状の状態をpushしておきました

**Comment by lachelier** [comment]
> ユーザーが複数いる部屋の場合誰を対象にすればいいんでしょうか？

フロント側で取得したいユーザを指定しますので、バックエンドでは気にせずに引数で渡されたユーザIDの情報を返していただければ大丈夫です:)

> これで大丈夫なんでしょうか、、、？

確認用でしたら今書いてあるところで大丈夫です！
実際には別のところで利用しますので、確認用コードは削除してプルリクをお送りください:)

**Comment by lachelier** [comment]
このIssueはAPIの作成（バックエンドのみ）なのでご対応不要ですが、たぶん気にしていらっしゃるので一応用途をお伝えしておくと
今のところ、参加者追加イベントが発生したときにユーザ情報を取得するために使用しようと思っています！（もしかしたら後で変えるかもしれません）

src/resources/js/components/partials/sugoroku.vue
```
mounted: function () {
        window.Echo.private('member-added-channel.' + this.room.id).listen('MemberAdded', response => {
            // response.userId
            // response.roomId
            // ここでAPIにアクセスして、取得したデータをthis.v_membersに追加
        });
}
```
