### ISSUE TITLE
👑サイコロを振る機能

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#91]
ゲームがスタートされた後、プレイ順にサイコロを振れるように実装をお願いします。
なお、プレイ順はゲームスタートされるとroom_userテーブルのgoカラムに保存されます。

Pusher / Echoは本番機にインストール済みです。

- サイコロを振るボタンはresources/js/components/partials/action.vueに設置
- ゲームがスタートしていなければサイコロボタンは表示されない
- 自分のターンでないときは、disabled
- 出た目はプライベートチャンネルに送信＆同じ部屋の参加者全員に配信

他なにか不足情報あれば聞いてください！

**Comment by stkzk3110** [comment]
質問です！
自分のターンでないかどうかってroom_userテーブルのgoカラムで判断する感じになりますかね🤔
多分現状、自分のターンかどうかをもつカラムってなかった気がするので。。。

**Comment by lachelier** [comment]
> 出た目はプライベートチャンネルに送信＆同じ部屋の参加者全員に配信
この配信にユーザIDやgoカラム情報等必要な情報も含めて（なにが最低限必要なのかの判断はお任せします。作りやすい方法にしてください）、自分の前のユーザがサイコロを振り終わったら自分のターンと判断する感じでお願いします！

**Comment by lachelier** [comment]
すみません、action.vueの内容はsugoroku.vueに統合しましたので、そちらに実装をお願いします💦
