### ISSUE TITLE
コマの現在地を返すAPIを作成

### ISSUE THREAD

**Issue by lachelier** [lachelier/sugoroku#93]
コマの現在地はroom_userテーブルのpositionに入ってます。
ログイン済みのユーザのみ取得できるようにお願いします！

**Comment by favopg** [comment]
@lachelier 
実装してみたのですが、流れが合っているかわからなかったのでコードを確認していただいてもよろしいでしょうか？
ブランチ名：feature/#93_issi_develop

実装が仮に正しくてもテストコードでpositionの確認結果が「１」になっちゃってるのでどうやって確認すれば良いかなと。。。
→コマの現在地はサイコロ振る毎に変わるはずなので、固定値になるわけないなーと思いまして、、、

お手数おかけいたしますが、ご確認ほどよろしくお願いいたします。
